name: chatq_docker

services:
  mongo:
    image: mongo:8
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --save 20 1
      - --loglevel warning
      - --requirepass ${REDIS_DB_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
